import { useMemo, useState } from 'react';
import vocabulary from '../content/vocabulary/a2/core.json';
import grammar from '../content/grammar/a2/curriculum.json';
import './styles.css';

type Lang = 'uk' | 'sk';
type Page = 'today' | 'vocabulary' | 'grammar' | 'mixed' | 'review' | 'progress';

type Word = (typeof vocabulary.items)[number];
type GrammarTopic = (typeof grammar.topics)[number];

const copy = {
  uk: { today:'Сьогодні', vocabulary:'Словник', grammar:'Граматика', mixed:'Змішана практика', review:'Повторення', progress:'Прогрес', title:'Словацька A2 — вчимо, а не просто читаємо', subtitle:'Короткі сесії: слова → правило → контекст → повторення.', startWords:'Вчити слова', startGrammar:'Вчити граматику', words:'слів у першому наборі', topics:'граматичних тем', reviewToday:'Повторити сьогодні', source:'A2 curriculum за Krížom-krážom', chooseTopic:'Оберіть тему', all:'Усі', cardHint:'Натисніть картку, щоб побачити переклад', example:'Приклад', collocation:'Сполучення', visual:'Візуальна ідея', rule:'ПРАВИЛО', examples:'Приклади', mixedTitle:'Слово + граматика + реальна ситуація', reviewTitle:'Помилка має навчати', progressTitle:'Ваш навчальний прогрес' },
  sk: { today:'Dnes', vocabulary:'Slovná zásoba', grammar:'Gramatika', mixed:'Mix tréning', review:'Opakovanie', progress:'Pokrok', title:'Slovenčina A2 — učíme sa, nielen čítame', subtitle:'Krátke lekcie: slovo → pravidlo → kontext → opakovanie.', startWords:'Učiť slovíčka', startGrammar:'Učiť gramatiku', words:'slov v prvom balíku', topics:'gramatických tém', reviewToday:'Opakovať dnes', source:'A2 curriculum podľa Krížom-krážom', chooseTopic:'Vyberte tému', all:'Všetky', cardHint:'Kliknite na kartu a zobrazí sa preklad', example:'Príklad', collocation:'Kolokácia', visual:'Vizuálny koncept', rule:'PRAVIDLO', examples:'Príklady', mixedTitle:'Slovo + gramatika + reálna situácia', reviewTitle:'Chyba musí učiť', progressTitle:'Váš študijný pokrok' }
} as const;

const topicIcons: Record<string,string> = {leisure:'🎯',sport:'🏃',travel:'🚆',city:'🏙️',communication:'💬',media:'📺',health:'🩺',shopping:'🛍️','food-shopping':'🥖',weather:'❄️',relationships:'👥',slovakia:'🇸🇰','slovakia-travel':'🗺️'};

export default function App(){
  const [lang,setLang]=useState<Lang>('uk');
  const [page,setPage]=useState<Page>('today');
  const t=copy[lang];
  const nav:[Page,string,string][]=[['today',t.today,'⌂'],['vocabulary',t.vocabulary,'◫'],['grammar',t.grammar,'◇'],['mixed',t.mixed,'↔'],['review',t.review,'↻'],['progress',t.progress,'↗']];
  return <div className="shell"><aside><button className="brand" onClick={()=>setPage('today')}><b>SK</b><span>Slovak A2 Trainer<small>SK + UA</small></span></button><nav>{nav.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sideCard"><span>A2</span><strong>{vocabulary.items.length} {t.words}</strong><small>{grammar.topics.length} {t.topics}</small></div></aside><main><header><span>A2 · Learning first</span><div className="lang"><button className={lang==='sk'?'on':''} onClick={()=>setLang('sk')}>SK</button><button className={lang==='uk'?'on':''} onClick={()=>setLang('uk')}>UA</button></div></header>{page==='today'&&<Today lang={lang} go={setPage}/>} {page==='vocabulary'&&<Vocabulary lang={lang}/>} {page==='grammar'&&<Grammar lang={lang}/>} {page==='mixed'&&<Mixed lang={lang}/>} {page==='review'&&<Review lang={lang}/>} {page==='progress'&&<Progress lang={lang}/>}</main></div>
}

function Today({lang,go}:{lang:Lang;go:(p:Page)=>void}){const t=copy[lang];return <div className="page"><section className="hero"><div><span className="eyebrow">SLOVENČINA · A2</span><h1>{t.title}</h1><p>{t.subtitle}</p><div className="actions"><button className="primary" onClick={()=>go('vocabulary')}>{t.startWords} →</button><button className="secondary" onClick={()=>go('grammar')}>{t.startGrammar}</button></div></div><div className="daily"><span>{t.reviewToday}</span><strong>12</strong><small>{lang==='uk'?'слів + 2 правила':'slov + 2 pravidlá'}</small></div></section><div className="metrics"><article><b>{vocabulary.items.length}</b><span>{t.words}</span></article><article><b>{grammar.topics.length}</b><span>{t.topics}</span></article><article><b>6</b><span>{lang==='uk'?'типів тренування':'typov tréningu'}</span></article></div><section className="two"><article className="panel feature"><span className="eyebrow">VOCABULARY</span><h2>{lang==='uk'?'Карточка → впізнавання → згадування → контекст':'Karta → rozpoznanie → vybavenie → kontext'}</h2><div className="miniCards">{vocabulary.items.slice(0,4).map(w=><span key={w.id}>{topicIcons[w.topic]||'●'} {w.wordSk}</span>)}</div><button className="text" onClick={()=>go('vocabulary')}>{t.startWords} →</button></article><article className="panel feature"><span className="eyebrow">VISUAL GRAMMAR</span><h2>{lang==='uk'?'Правило треба побачити':'Pravidlo treba vidieť'}</h2><div className="grammarVisual"><span>KAM? →</span><b>na univerzitu</b><span>KDE? ●</span><b>na univerzite</b></div><button className="text" onClick={()=>go('grammar')}>{t.startGrammar} →</button></article></section><p className="sourceNote">{t.source}</p></div>}

function Vocabulary({lang}:{lang:Lang}){const t=copy[lang];const topics=useMemo(()=>['all',...Array.from(new Set(vocabulary.items.map(x=>x.topic)))],[]);const [topic,setTopic]=useState('all');const [open,setOpen]=useState<string|null>(null);const words=topic==='all'?vocabulary.items:vocabulary.items.filter(x=>x.topic===topic);return <div className="page"><span className="eyebrow">A2 · VOCABULARY</span><h1>{t.vocabulary}</h1><p className="lead">{t.cardHint}</p><div className="filters">{topics.map(x=><button key={x} className={topic===x?'selected':''} onClick={()=>setTopic(x)}>{x==='all'?t.all:x}</button>)}</div><div className="wordGrid">{words.map((w:Word)=><button className={'wordCard '+(open===w.id?'flipped':'')} key={w.id} onClick={()=>setOpen(open===w.id?null:w.id)}><div className="wordIcon">{topicIcons[w.topic]||'Aa'}</div><span className="level">A2</span><h2>{w.wordSk}</h2>{open===w.id?<><strong className="translation">{w.translationUk}</strong><p>{w.example}</p><small>{w.collocations[0]}</small></>:<><p>{w.topic}</p><small>{w.grammar}</small></>}</button>)}</div></div>}

function Grammar({lang}:{lang:Lang}){const t=copy[lang];const [selected,setSelected]=useState<GrammarTopic>(grammar.topics[0]);return <div className="page"><span className="eyebrow">A2 · VISUAL GRAMMAR</span><h1>{t.grammar}</h1><div className="grammarLayout"><div className="topicList">{grammar.topics.map((g:GrammarTopic)=><button key={g.id} className={selected.id===g.id?'selected':''} onClick={()=>setSelected(g)}><span>{String(g.lesson).padStart(2,'0')}</span><b>{g.title[lang]}</b><small>{g.group}</small></button>)}</div><article className="lesson"><span className="level">LEKCIA {selected.lesson}</span><h2>{selected.title[lang]}</h2><p className="lead small">{selected.summary[lang]}</p><div className="infographic"><span>VISUAL</span><strong>{selected.visual}</strong><div className="arrow">→</div><em>{selected.examples[0]}</em></div>{selected.rules.length>0&&<div className="rule"><b>{t.rule}</b><p>{selected.rules[0]}</p></div>}<h3>{t.examples}</h3><div className="exampleChips">{selected.examples.map(x=><span key={x}>{x}</span>)}</div></article></div></div>}

function Mixed({lang}:{lang:Lang}){const t=copy[lang];return <div className="page narrow"><span className="eyebrow">MIXED PRACTICE</span><h1>{t.mixedTitle}</h1><article className="exercise"><div className="scene">🚆 <span>Bratislava</span></div><h2>Cestujem do Bratislavy ___.</h2><div className="answers"><button>vlak</button><button>vlaku</button><button className="correct">vlakom ✓</button><button>vlaky</button></div><div className="teach"><b>{t.rule}</b><p>{lang==='uk'?'Чим їду? Засіб транспорту вживаємо в Instrumentáli: vlak → vlakom, autobus → autobusom.':'Čím cestujem? Dopravný prostriedok používame v inštrumentáli: vlak → vlakom, autobus → autobusom.'}</p></div></article></div>}

function Review({lang}:{lang:Lang}){const t=copy[lang];return <div className="page narrow"><span className="eyebrow">REVIEW / MISTAKES</span><h1>{t.reviewTitle}</h1><article className="mistake"><div className="bad">✕ idem</div><div className="good">✓ išiel</div><h2>Včera som ___ do práce.</h2><div className="rule"><b>{t.rule}</b><p>{lang==='uk'?'Včera позначає минулу подію. Для ja: som + форма минулого часу. І виняток: ísť → išiel / išla / išli.':'Včera označuje minulý dej. Pre ja: som + minulý tvar. Výnimka: ísť → išiel / išla / išli.'}</p></div><button className="primary">{lang==='uk'?'Тренувати це правило':'Precvičiť toto pravidlo'} →</button></article></div>}

function Progress({lang}:{lang:Lang}){const t=copy[lang];return <div className="page"><span className="eyebrow">PROGRESS</span><h1>{t.progressTitle}</h1><div className="metrics big"><article><b>0</b><span>NEW</span></article><article><b>18</b><span>LEARNING</span></article><article><b>14</b><span>FAMILIAR</span></article><article><b>8</b><span>LEARNED</span></article></div><section className="panel"><h2>{lang==='uk'?'Що повторювати далі':'Čo opakovať ďalej'}</h2><div className="progressRow"><span>Vocabulary · šport</span><b>62%</b></div><div className="bar"><i style={{width:'62%'}}/></div><div className="progressRow"><span>Grammar · datív</span><b>38%</b></div><div className="bar"><i style={{width:'38%'}}/></div></section></div>}
